trigger:
  branches:
    include:
      - main

pool:
  name: SelfHosted

stages:
- stage: CI
  displayName: CI Front & Back
  jobs:
  - job: Front
    displayName: Build Front (Vite)   
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - script: echo "MARKER v5 - $(Build.SourceVersion)"
        displayName: Marker
      - script: node -v && npm -v
        displayName: Check Node/NPM
      - script: |
          npm ci
          npm run build
          ls -la
          ls -la dist
        workingDirectory: front
        displayName: install & build (front)
      - task: CopyFiles@2
        displayName: Copiar dist a staging
        inputs:
          SourceFolder: 'front/dist'
          Contents: '**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)/front-dist'
      - task: PublishBuildArtifacts@1
        displayName: Publicar artefacto front (dist)
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/front-dist'
          ArtifactName: 'front-dist'
          publishLocation: 'Container'


  - job: Back
    displayName: Build Back (Node)
    steps:
    - script: node -v && npm -v
      displayName: Check Node/NPM
    - script: |
        cd back
        npm ci
        npm test
        npm run build
      displayName: test & build (back)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'back/bin'
        ArtifactName: 'back-bin'
        publishLocation: 'Container'
      displayName: Publicar artefacto back (bin)