trigger:
  branches:
    include:
      - main

pool:
  name: SelfHosted   # <- Usar tu agente propio

stages:
- stage: CI
  displayName: CI Front & Back
  jobs:
  - job: Front
    displayName: Build Front (Vite)
    steps:
    - checkout: self

    # Asegura Node 20.x (recomendado para Vite 7)
    - task: NodeTool@0
      displayName: Use Node 20.x
      inputs:
        versionSpec: '20.x'
        checkLatest: true

    - script: |
        node -v
        npm -v
      displayName: Check Node/NPM

    - script: |
        npm ci
        npm run build
      workingDirectory: front
      displayName: install & build (front)

    - task: PublishBuildArtifacts@1
      displayName: Publicar artefacto front (dist)
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\front\dist'
        ArtifactName: 'front-dist'
        publishLocation: 'Container'

  - job: Back
    displayName: Build Back (Node)
    steps:
    - script: node -v && npm -v
      displayName: Check Node/NPM
    - script: |
        cd back
        npm ci
        npm test
        npm run build
      displayName: test & build (back)
    - task: PublishBuildArtifacts@1
      displayName: Publicar artefacto back (bin)
      inputs:
        PathtoPublish: 'back/bin'
        ArtifactName: 'back-bin'
        publishLocation: 'Container'
