trigger:
  branches:
    include:
      - main

pool:
  name: SelfHosted

stages:
- stage: CI
  displayName: CI Front & Back
  jobs:
  - job: Front
    displayName: Build Front (Vite)
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
    - script: |
        npm ci
        npm run build
      workingDirectory: front
      displayName: build front
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\front\dist'
        ArtifactName: 'front-dist'
        publishLocation: 'Container'
      displayName: publish front

  - job: Back
    displayName: Build Back (Node)
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
    - script: |
        npm ci
        npm test
        npm run build
      workingDirectory: back
      displayName: build back
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\back\bin'
        ArtifactName: 'back-bin'
        publishLocation: 'Container'
      displayName: publish back
